### ISSUE TITLE
[android] crash during video export on emulator

### ISSUE THREAD

**Issue by freeboub** [AzzappApp/react-native-skia-video#12]
On emulator, during video export,
a Maximum call stack size exceeded (native stack depth) sometimes happen

See following callstack:

09-24 13:29:59.584  9504  9558 D EGL_emulation: app_time_stats: avg=7.58ms min=2.55ms max=23.37ms count=61
09-24 13:29:59.815  9504  9865 D EGL_emulation: app_time_stats: avg=63.03ms min=53.18ms max=79.49ms count=16
09-24 13:29:59.836  9504  9634 E ReactNativeJS: ReanimatedError: Maximum call stack size exceeded (native stack depth), js engine: reanimated
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: Error while exporting
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: com.facebook.jni.CppException: Maximum call stack size exceeded (native stack depth)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: No stack
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.renderFrame(Native Method)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrame(VideoCompositionExporter.java:200)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrameIfReady(VideoCompositionExporter.java:193)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.checkIfFrameDecoded(VideoCompositionExporter.java:167)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrame(VideoCompositionExporter.java:207)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrameIfReady(VideoCompositionExporter.java:193)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.checkIfFrameDecoded(VideoCompositionExporter.java:167)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrame(VideoCompositionExporter.java:207)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrameIfReady(VideoCompositionExporter.java:193)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.checkIfFrameDecoded(VideoCompositionExporter.java:167)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrame(VideoCompositionExporter.java:207)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrameIfReady(VideoCompositionExporter.java:193)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.checkIfFrameDecoded(VideoCompositionExporter.java:167)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrame(VideoCompositionExporter.java:207)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrameIfReady(VideoCompositionExporter.java:193)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.checkIfFrameDecoded(VideoCompositionExporter.java:167)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrame(VideoCompositionExporter.java:207)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrameIfReady(VideoCompositionExporter.java:193)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.checkIfFrameDecoded(VideoCompositionExporter.java:167)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrame(VideoCompositionExporter.java:207)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrameIfReady(VideoCompositionExporter.java:193)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.checkIfFrameDecoded(VideoCompositionExporter.java:167)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrame(VideoCompositionExporter.java:207)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrameIfReady(VideoCompositionExporter.java:193)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.checkIfFrameDecoded(VideoCompositionExporter.java:167)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrame(VideoCompositionExporter.java:207)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.writeFrameIfReady(VideoCompositionExporter.java:193)
09-24 13:29:59.847  9504  9865 E ReactNativeSkiaVideo: 	at com.azzapp.rnskv.VideoCompositionExporter.checkIfFrameDecoded(VideoCompositionExporter.java:167)

app is finnally stopped with a segv:
09-24 13:30:00.943  9504  9504 I ReactNative: [GESTURE HANDLER] Initialize gesture handler for root view com.facebook.react.ReactRootView{13c4319 V.E...... .......D 0,0-1080,2337 #b}
09-24 13:30:01.399  9881  9881 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-24 13:30:01.399  9881  9881 F DEBUG   : Build fingerprint: 'google/sdk_gphone64_arm64/emu64a:15/AE3A.240806.005/12228598:user/release-keys'
09-24 13:30:01.399  9881  9881 F DEBUG   : Revision: '0'
09-24 13:30:01.399  9881  9881 F DEBUG   : ABI: 'arm64'
09-24 13:30:01.399  9881  9881 F DEBUG   : Timestamp: 2024-09-24 13:30:00.183819022+0200
09-24 13:30:01.399  9881  9881 F DEBUG   : Process uptime: 84s
09-24 13:30:01.399  9881  9881 F DEBUG   : Cmdline: 
09-24 13:30:01.399  9881  9881 F DEBUG   : pid: 9504, tid: 9865, name: ReactNativeSkia  >>>  <<<
09-24 13:30:01.399  9881  9881 F DEBUG   : uid: 10206
09-24 13:30:01.399  9881  9881 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
09-24 13:30:01.399  9881  9881 F DEBUG   : pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
09-24 13:30:01.403  9881  9881 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000018
09-24 13:30:01.403  9881  9881 F DEBUG   : Cause: null pointer dereference
09-24 13:30:01.403  9881  9881 F DEBUG   :     x0  0000000000000000  x1  0000007afb1ca020  x2  0000007af3985484  x3  0000007799f3b5c8
09-24 13:30:01.403  9881  9881 F DEBUG   :     x4  00000000000000a0  x5  0000007990a2cbec  x6  0000000000023177  x7  00000b9020000000
09-24 13:30:01.403  9881  9881 F DEBUG   :     x8  cd5324d3294c4200  x9  0000000001f14000  x10 0000000000000015  x11 00000000000a0008
09-24 13:30:01.403  9881  9881 F DEBUG   :     x12 b400007861418b08  x13 0000000000000000  x14 0000000000000000  x15 0000000000000000
09-24 13:30:01.403  9881  9881 F DEBUG   :     x16 00000077af53cae8  x17 00000077f86f7138  x18 00000076c3e18000  x19 0000000000000000
09-24 13:30:01.403  9881  9881 F DEBUG   :     x20 0000007799f3b730  x21 0000007799f3ba80  x22 0000000000002520  x23 00000000000025a2
09-24 13:30:01.403  9881  9881 F DEBUG   :     x24 0000007799f3b730  x25 0000007799f3b730  x26 0000007799f3ba70  x27 b4000078f0c3fc70
09-24 13:30:01.403  9881  9881 F DEBUG   :     x28 0000007799e37000  x29 0000007799f3b5c0
09-24 13:30:01.403  9881  9881 F DEBUG   :     lr  00000077af52fc1c  sp  0000007799f3b5a0  pc  00000077f86f715c  pst 0000000020001000
09-24 13:30:01.403  9881  9881 F DEBUG   : 3 total frames
09-24 13:30:01.403  9881  9881 F DEBUG   : backtrace:
09-24 13:30:01.403  9881  9881 F DEBUG   :       #00 pc 00000000000e215c  /vendor/lib64/libOpenglSystemCommon.so (HostConnection::gl2Encoder()+36) (BuildId: e946353d630bf30ff53bb69b407702bc)
09-24 13:30:01.403  9881  9881 F DEBUG   :       #01 pc 0000000000010c18  /vendor/lib64/egl/libGLESv2_emulation.so (glFinish+16) (BuildId: 8ac2705a77ba9aa113bdd2de128deae0)
09-24 13:30:01.403  9881  9881 F DEBUG   :       #02 pc 0000000000b60304  /data/app/~~ZfakNjA8Mruyw2mSUrQ2MQ==/XXXX-E2v-cnik8pMOYxkZbTd77w==/base.apk!librnskia.so (offset 0x5d88000) (BuildId: 6cf82e072b8ede6ae461b8f2abaabbc7e47a26ef)

**Comment by fdecampredon** [comment]
@freeboub please test if this issue is still valid in 0.8

**Comment by freeboub** [comment]
@fdecampredon I cannot reproduce this issue with the sample. so we can close.
To work with the sample on emulator, I need to apply this patch : https://github.com/AzzappApp/react-native-skia-video/pull/16
BTW, I am still not able to export more than 2 videos with the sample app
Let's close this issue
